export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED';
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED';
export const APP_LOAD = 'APP_LOAD';
export const LOGIN = 'LOGIN';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';